# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.domain_success_response import DomainSuccessResponse

class TestDomainSuccessResponse(unittest.TestCase):
    """DomainSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainSuccessResponse:
        """Test DomainSuccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainSuccessResponse`
        """
        model = DomainSuccessResponse()
        if include_optional:
            return DomainSuccessResponse(
                message = ''
            )
        else:
            return DomainSuccessResponse(
        )
        """

    def testDomainSuccessResponse(self):
        """Test DomainSuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
