# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_core_api_client.models.domain_company_function import DomainCompanyFunction

class TestDomainCompanyFunction(unittest.TestCase):
    """DomainCompanyFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainCompanyFunction:
        """Test DomainCompanyFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainCompanyFunction`
        """
        model = DomainCompanyFunction()
        if include_optional:
            return DomainCompanyFunction(
                description = '',
                level = 56,
                name = ''
            )
        else:
            return DomainCompanyFunction(
        )
        """

    def testDomainCompanyFunction(self):
        """Test DomainCompanyFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
