# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_core_api_client.api.chats_api import ChatsApi


class TestChatsApi(unittest.TestCase):
    """ChatsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatsApi()

    def tearDown(self) -> None:
        pass

    def test_chats_get(self) -> None:
        """Test case for chats_get

        Get all client chats of company
        """
        pass


if __name__ == '__main__':
    unittest.main()
