# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.domain_conversation_response import DomainConversationResponse

class TestDomainConversationResponse(unittest.TestCase):
    """DomainConversationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainConversationResponse:
        """Test DomainConversationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainConversationResponse`
        """
        model = DomainConversationResponse()
        if include_optional:
            return DomainConversationResponse(
                content = '',
                tools = [
                    openapi_client.models.domain/ai_tool.domain.AITool(
                        function = openapi_client.models.domain/ai_function_call.domain.AIFunctionCall(
                            arguments = '', 
                            name = '', ), 
                        id = '', 
                        index = 56, 
                        type = '', )
                    ]
            )
        else:
            return DomainConversationResponse(
        )
        """

    def testDomainConversationResponse(self):
        """Test DomainConversationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
