# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_core_api_client.models.domain_get_me_response import DomainGetMeResponse

class TestDomainGetMeResponse(unittest.TestCase):
    """DomainGetMeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainGetMeResponse:
        """Test DomainGetMeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainGetMeResponse`
        """
        model = DomainGetMeResponse()
        if include_optional:
            return DomainGetMeResponse(
                functions = [
                    openapi_client.models.domain/company_function.domain.CompanyFunction(
                        description = '', 
                        level = 56, 
                        name = '', )
                    ],
                id = '',
                level = 56,
                name = '',
                prompt_blocks = [
                    openapi_client.models.domain/prompt_block.domain.PromptBlock(
                        content = '', 
                        name = '', )
                    ]
            )
        else:
            return DomainGetMeResponse(
        )
        """

    def testDomainGetMeResponse(self):
        """Test DomainGetMeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
