# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_core_api_client.api.company_api import CompanyApi


class TestCompanyApi(unittest.TestCase):
    """CompanyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompanyApi()

    def tearDown(self) -> None:
        pass

    def test_company_get(self) -> None:
        """Test case for company_get

        Returns a list of companies
        """
        pass

    def test_company_id_delete(self) -> None:
        """Test case for company_id_delete

        Delete company from the database
        """
        pass

    def test_company_id_get(self) -> None:
        """Test case for company_id_get

        Get company details
        """
        pass

    def test_company_post(self) -> None:
        """Test case for company_post

        Adds a company to the database
        """
        pass


if __name__ == '__main__':
    unittest.main()
