# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_core_api_client.api.get_me_api import GetMeApi


class TestGetMeApi(unittest.TestCase):
    """GetMeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetMeApi()

    def tearDown(self) -> None:
        pass

    def test_get_me_get(self) -> None:
        """Test case for get_me_get

        Get company details
        """
        pass


if __name__ == '__main__':
    unittest.main()
