# coding: utf-8

"""
    AISF API

    This API gives you the ability to interact with AISF's neural networks

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_core_api_client.models.domain_get_chats_response import DomainGetChatsResponse

class TestDomainGetChatsResponse(unittest.TestCase):
    """DomainGetChatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainGetChatsResponse:
        """Test DomainGetChatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainGetChatsResponse`
        """
        model = DomainGetChatsResponse()
        if include_optional:
            return DomainGetChatsResponse(
                chats = [
                    openapi_client.models.domain/client_chat.domain.ClientChat(
                        client_id = 56, 
                        messages = [
                            openapi_client.models.domain/client_message.domain.ClientMessage(
                                client_id = 56, 
                                content = '', 
                                date = '', 
                                event_id = 56, 
                                message_id = 56, )
                            ], )
                    ]
            )
        else:
            return DomainGetChatsResponse(
        )
        """

    def testDomainGetChatsResponse(self):
        """Test DomainGetChatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
